<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ds_page_icon"
 *
 * Auto generated by Extension Builder 2014-03-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'page icon',
	'description' => 'Adds option to associate an icon to a page.',
	'category' => 'misc',
	'author' => 'Daniel Schöne',
	'author_email' => 'daniel@schoene.it',
	'author_company' => 'schoene.it',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '7.6.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
